const seedMenu = [
  { _id: 'oysters', name: 'Atlantic Oysters', description: 'Cold Atlantic oysters with sharp mignonette and preserved lemon.', price: '120 MAD', category: "Tonight's catch", available: true, dietary: 'Gluten-free', allergens: ['Shellfish'], ingredients: ['Atlantic oysters', 'Shallot', 'Red wine vinegar', 'Preserved lemon', 'Black pepper', 'Coastal herbs'], preparation: 'Shucked to order and served over crushed ice with our preserved-lemon mignonette.', image: 'https://images.pexels.com/photos/10375841/pexels-photo-10375841.jpeg?auto=compress&cs=tinysrgb&w=1200' },
  { _id: 'bass', name: 'Sea Bass Crudo', description: 'Line-caught bass, citrus, green olive oil and sea salt.', price: '145 MAD', category: "Tonight's catch", available: true, dietary: 'Gluten-free', allergens: ['Fish'], ingredients: ['Atlantic sea bass', 'Orange', 'Lemon', 'Extra-virgin olive oil', 'Sea salt', 'Coriander seed'], preparation: 'The bass is sliced at the last moment, lightly cured with citrus and finished with Moroccan olive oil.', image: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&w=1200&q=85' },
  { _id: 'sardines', name: 'Sardines & Chermoula', description: 'Agadir sardines, green chermoula and grilled bread.', price: '110 MAD', category: "Tonight's catch", available: true, dietary: 'Dairy-free', allergens: ['Fish', 'Gluten'], ingredients: ['Fresh sardines', 'Coriander', 'Parsley', 'Cumin', 'Paprika', 'Garlic', 'Lemon', 'Sourdough'], preparation: 'Butterflied sardines are marinated in chermoula, flashed over charcoal and served with grilled sourdough.', image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?auto=format&fit=crop&w=1200&q=85' },
  { _id: 'octopus', name: 'Charcoal Octopus', description: 'Tender octopus, chermoula, smoke and burnt lemon.', price: '190 MAD', category: 'From the fire', available: true, dietary: 'Gluten-free', allergens: ['Molluscs'], ingredients: ['Atlantic octopus', 'Coriander', 'Parsley', 'Garlic', 'Cumin', 'Smoked paprika', 'Lemon', 'Olive oil'], preparation: 'Slow-tenderised, then finished directly over charcoal until the edges are crisp and smoky.', image: 'https://images.pexels.com/photos/4846391/pexels-photo-4846391.jpeg?auto=compress&cs=tinysrgb&w=1200' },
  { _id: 'dorade', name: 'Whole Grilled Dorade', description: 'Whole local dorade with fennel, herbs and preserved citrus.', price: '220 MAD', category: 'From the fire', available: true, dietary: 'Gluten-free', allergens: ['Fish'], ingredients: ['Whole dorade', 'Fennel', 'Parsley', 'Preserved lemon', 'Garlic', 'Olive oil', 'Sea salt'], preparation: 'Scored, seasoned and grilled whole over olive wood, then dressed with warm fennel and citrus oil.', image: 'https://images.pexels.com/photos/3296279/pexels-photo-3296279.jpeg?auto=compress&cs=tinysrgb&w=1200' },
  { _id: 'lobster', name: 'Atlantic Lobster', description: 'Fire-roasted lobster, brown butter and coastal herbs.', price: 'Market', category: 'From the fire', available: true, dietary: 'Gluten-free', allergens: ['Shellfish', 'Dairy'], ingredients: ['Atlantic lobster', 'Cultured butter', 'Tarragon', 'Parsley', 'Garlic', 'Lemon'], preparation: 'Split to order, roasted over flame and basted with nutty brown butter and fresh coastal herbs.', image: 'https://images.pexels.com/photos/7741270/pexels-photo-7741270.jpeg?auto=compress&cs=tinysrgb&w=1200' },
  { _id: 'tagine', name: 'Seafood Tagine', description: 'Shellfish and market fish in a saffron tomato broth.', price: '185 MAD', category: 'For the table', available: true, dietary: 'Gluten-free', allergens: ['Fish', 'Shellfish', 'Molluscs'], ingredients: ['Market fish', 'Prawns', 'Mussels', 'Tomato', 'Saffron', 'Ginger', 'Garlic', 'Coriander'], preparation: 'Cooked slowly in clay so the saffron broth gathers the sweetness of each piece of seafood.', image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=1200&q=85' },
  { _id: 'potatoes', name: 'Sea-Salt Potatoes', description: 'Crisp potatoes, smoked aioli and preserved lemon.', price: '65 MAD', category: 'For the table', available: true, dietary: 'Vegetarian', allergens: ['Egg'], ingredients: ['Baby potatoes', 'Sea salt', 'Egg yolk', 'Garlic', 'Smoked paprika', 'Preserved lemon'], preparation: 'Twice-cooked until crisp, then tossed with sea salt and served beside smoked aioli.', image: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&w=1200&q=85' },
]

const createStore = () => ({ menu: structuredClone(seedMenu), reservations: [] })
export const store = globalThis.__mareStoreV2 || createStore()
if (process.env.NODE_ENV !== 'production') globalThis.__mareStoreV2 = store

export function reference() { return `MARE-${Math.random().toString(36).slice(2, 8).toUpperCase()}` }
