'use client'

import { useEffect,useMemo,useState } from 'react'
import { api } from './api'
const slug='mare',tokenKey='mare-owner-token',statuses=['confirmed','completed','cancelled','no-show']
export default function Admin(){
 const [token,setToken]=useState(()=>typeof window==='undefined'?'':window.sessionStorage.getItem(tokenKey)||''),[view,setView]=useState('overview'),[menu,setMenu]=useState([]),[reservations,setReservations]=useState([]),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const auth=(path,options={})=>api(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}})
 const load=async()=>{if(!token)return;setBusy(true);try{const [m,r]=await Promise.all([auth('/api/admin/mare/menu'),auth('/api/admin/mare/reservations')]);setMenu(m);setReservations(r);setMessage('')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(!token)return;let active=true;Promise.all([api('/api/admin/mare/menu',{headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}}),api('/api/admin/mare/reservations',{headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}})]).then(([m,r])=>{if(!active)return;setMenu(m);setReservations(r);setMessage('')}).catch(error=>active&&setMessage(error.message)).finally(()=>active&&setBusy(false));return()=>{active=false}},[token])
 const login=async e=>{e.preventDefault();setBusy(true);try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});if(!result.user.restaurants.some(r=>r.slug===slug))throw new Error('This account does not have access to MARÉ.');sessionStorage.setItem(tokenKey,result.token);setToken(result.token)}catch(error){setMessage(error.message)}finally{setBusy(false)}}
 const mutate=async task=>{setBusy(true);try{await task();await load()}catch(e){setMessage(e.message);setBusy(false)}}
 const updateMenu=(item,changes)=>mutate(()=>auth(`/api/admin/mare/menu/${item._id}`,{method:'PATCH',body:JSON.stringify(changes)}))
 const removeMenu=item=>confirm(`Remove “${item.name}” from the menu?`)&&mutate(()=>auth(`/api/admin/mare/menu/${item._id}`,{method:'DELETE'}))
 const addMenu=e=>{e.preventDefault();const form=e.currentTarget;mutate(()=>auth('/api/admin/mare/menu',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))})).then(()=>form.reset())}
 const updateReservation=(id,status)=>mutate(()=>auth(`/api/admin/mare/reservations/${id}`,{method:'PATCH',body:JSON.stringify({status})}))
 const today=new Date().toISOString().slice(0,10),upcoming=reservations.filter(r=>r.date>=today&&r.status==='confirmed'),covers=upcoming.reduce((n,r)=>n+r.guests,0)
 const filtered=useMemo(()=>reservations.filter(r=>`${r.name} ${r.phone} ${r.reference} ${r.date}`.toLowerCase().includes(query.toLowerCase())),[reservations,query])
 if(!token)return <main className="mare-login"><section><a href="/">MARÉ</a><div><p>PRIVATE OFFICE · ATLANTIC COAST</p><h1>Run with<br/>the <em>tide.</em></h1><span>Reservations, menus and the rhythm of service.</span></div><small>AGADIR · MOROCCO</small></section><form onSubmit={login}><p>OWNER ACCESS</p><h2>Welcome ashore.</h2><label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" minLength="8" required/></label><button disabled={busy}>{busy?'Opening…':'Enter dashboard'}<span>↗</span></button>{message&&<small>{message}</small>}<a href="/">← Return to MARÉ</a></form></main>
 return <div className="mare-office"><aside><a className="mare-mark" href="/">MARÉ</a><nav>{[['overview','Overview'],['reservations','Reservations'],['menu','Tonight’s menu']].map(([id,label],i)=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}><small>0{i+1}</small>{label}</button>)}</nav><div className="mare-profile"><i>M</i><div><b>MARÉ Owner</b><span>Atlantic office</span></div></div><button className="mare-signout" onClick={()=>{sessionStorage.removeItem(tokenKey);setToken('')}}>Sign out</button></aside><main><header><div><p>OWNER DASHBOARD · AGADIR</p><h1>{view==='overview'?'Today, at a glance.':view==='menu'?<>Tonight’s <em>catch.</em></>:<>The <em>tables.</em></>}</h1></div><a href="/" target="_blank">View website ↗</a></header>{message&&<div className="mare-notice">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 {view==='overview'&&<><section className="mare-metrics"><article><span>01</span><p>UPCOMING TABLES</p><strong>{upcoming.length}</strong><small>Confirmed reservations</small></article><article><span>02</span><p>EXPECTED COVERS</p><strong>{covers}</strong><small>Guests on the books</small></article><article><span>03</span><p>MENU LIVE</p><strong>{menu.filter(x=>x.available).length}<sup>/{menu.length}</sup></strong><small>Dishes available tonight</small></article></section><section className="mare-panel"><PanelHead eyebrow="NEXT ARRIVALS" title="Service ahead." action={()=>setView('reservations')}/><Bookings rows={upcoming.slice(0,5)} change={updateReservation}/></section></>}
 {view==='reservations'&&<section className="mare-panel"><div className="mare-panel-head"><div><p>RESERVATION BOOK</p><h2>Every guest.</h2></div><label className="mare-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or reference"/></label></div><Bookings rows={filtered} change={updateReservation}/></section>}
 {view==='menu'&&<section className="mare-panel"><div className="mare-panel-head"><div><p>LIVE WEBSITE CONTENT</p><h2>Edit the catch.</h2></div><span>{menu.filter(x=>x.available).length} dishes live</span></div><form className="mare-create" onSubmit={addMenu}><div><b>ADD A DISH</b><small>Publish something new from the kitchen.</small></div><input name="name" placeholder="Dish name" required/><input name="category" placeholder="Category"/><input name="description" placeholder="Description"/><input name="ingredients" placeholder="Ingredients, comma separated"/><input name="price" placeholder="Price"/><input name="image" placeholder="Image URL"/><button>Add +</button></form><div className="mare-dishes">{menu.map((item,i)=><article key={item._id}><span>{String(i+1).padStart(2,'0')}</span><div className="mare-thumb">{item.image?<img src={item.image} alt=""/>:'M'}</div><div className="mare-fields"><input defaultValue={item.name} onBlur={e=>e.target.value!==item.name&&updateMenu(item,{name:e.target.value})}/><input defaultValue={item.description} placeholder="Description" onBlur={e=>e.target.value!==item.description&&updateMenu(item,{description:e.target.value})}/><input defaultValue={item.price} placeholder="Price" onBlur={e=>e.target.value!==item.price&&updateMenu(item,{price:e.target.value})}/><input defaultValue={(item.ingredients||[]).join(', ')} placeholder="Ingredients" onBlur={e=>e.target.value!==(item.ingredients||[]).join(', ')&&updateMenu(item,{ingredients:e.target.value})}/></div><button className={`mare-live ${item.available?'on':''}`} onClick={()=>updateMenu(item,{available:!item.available})}><i/>{item.available?'Live':'Hidden'}</button><button className="mare-remove" onClick={()=>removeMenu(item)}>×</button></article>)}</div></section>}{busy&&<div className="mare-saving">Saving</div>}</main></div>
}
function PanelHead({eyebrow,title,action}){return <div className="mare-panel-head"><div><p>{eyebrow}</p><h2>{title}</h2></div><button onClick={action}>See all ↗</button></div>}
function Bookings({rows,change}){return rows.length?<div className="mare-bookings"><div className="mare-table-head"><span>Guest</span><span>Date & time</span><span>Party</span><span>Table</span><span>Status</span></div>{rows.map(r=><article key={r._id}><div><b>{r.name}</b><small>{r.phone}<br/>{r.reference}</small></div><div><b>{r.date}</b><small>{r.time}</small></div><b>{r.guests} guests</b><span>{r.table?.name||'—'} · {r.table?.area||'Room'}</span><select className={r.status} value={r.status} onChange={e=>change(r._id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></article>)}</div>:<div className="mare-empty"><b>○</b><h3>Calm waters.</h3><p>No reservations match this view yet.</p></div>}
